### ISSUE TITLE
Protovis example at the top of page 17

### ISSUE THREAD

**Issue by DDucks** [ptwobrussell/Mining-the-Social-Web#2]
Hi Matthew

I've been trying out the protovis example at the top of page 17 and the generated file (which incidentally is named ....HTML.HTML) refuses to display anything (in FF 3.6.2).

I can't see how to attach the file to this post.  I would be very grateful for your comments on the file as I'm rather stuck, so could you please tell me how to get it to you.- perhaps via the  oreilly address in the book i.e. http://getsatisfaction.com/oreilly or a direct email?

Many Thanks

David Rush

**Comment by ptwobrussell** [comment]
Feel free to email it to my username at zaffra.com and I'll be glad to take a look and help you sort it out. The example number you are working from would also be helpful I'm stepping out for dinner now but will do my best to respond in a few hours when I get back.

**Comment by ikari-pl** [comment]
I've found out during my own experiments (with data from my code, not these examples though), that Protovis (its force-directed graph) is very "touchy" where there is anything wrong with the data (for example, if you create a link between two nodes and one of them doesn't exist (the number is higher than node count), then nothing gets displayed, not even an error in console), and it gets _very_ unstable with over 90 nodes (actually around 90 is enough to crash the visualisation)...
