### ISSUE TITLE
couchdb-lucene "Search Timed Out"

### ISSUE THREAD

**Issue by tomas-aftalion** [ptwobrussell/Mining-the-Social-Web#27]
In case anyone is having trouble with "mailboxes__participants_in_conversations.py" due to timeout (and still having the 300000 secs in local.ini of couched) try adding "stale=ok" to the request:

conn.request('GET', '/%s/_fti/_design/lucene/%s?q=%s&limit=50000&stale=ok'

It worked for me. Hope it helps.

**Comment by ptwobrussell** [comment]
Thanks! (BTW - the 2nd Edition of Mining the Social Web that I'm working on will make a lot of things _much_ simpler. I apologize for the headaches that CouchDB and couchdb-lucene may have caused.)
