### ISSUE TITLE
SyntaxError in Ex 1-12 and when using 'except IndexError:'

### ISSUE THREAD

**Issue by sp00** [ptwobrussell/Mining-the-Social-Web#28]
Hi :)

I'm working through the examples in MTSW in example 1-12 

OUT="snl_search_results.dot
try:  
    nx.drawing.write_dot(g, OUT) except Importer, e:
        dot=['"%s" -> "%s" [tweet_id=%s]' % (n1, n2, g[n1][n2]['tweet_id']) \
        for n1,n2 in g.edges()]
        f=open(OUT, 'w')
        f.write(strict digraph {\n%s\n}' % (';\n' .join(dot),))
        f.close()
   ...:         

  File "<ipython-input-1-60acf634bab8>", line 2
    nx.drawing.write_dot(g, OUT) 

except Importer, e:
                                      ^
SyntaxError: invalid syntax

Then I moved to a different example 2-2
import sys
import urllib2
import HTMLParser
from BeautifulSoup import BeautifulSoup
URL=sys.argv[1]

and get the following error

---

IndexError                                Traceback (most recent call last)
/Library/Frameworks/<ipython-input-6-497f7e54285e> in <module>()
----> 1 URL=sys.argv[1]

IndexError: list index out of range

can you help please?

Thanks in advance

Lee

**Comment by ptwobrussell** [comment]
Regarding the syntax error in Example 1-12, it looks as though you've missed a closing quote at the very end of the line beginning with OUT

Regarding the issue with Example 2-2, you'll need to pass in a command line argument that's the URL that you want the script to read in (which is what sys.argv[1] represents), or you can redefine that line to say URL="http:// ..." and not pass in an argument.

Hope that helps.

**Comment by ptwobrussell** [comment]
Hopefully, this advice helped. Please re-open if you need additional help.
