### ISSUE TITLE
IOError: [Errno 22] invalid mode ('r') or filename: url

### ISSUE THREAD

**Issue by 4949Rodrigo** [ptwobrussell/Mining-the-Social-Web#32]
This error appears when I try to pass a url to apply the TF-IDF with the code:

plus__tf_idf_nltk

and

buzz__tf_idf_nltk

I'm sorry my english...

**Comment by ptwobrussell** [comment]
Can you provide a full console dump of your exact command and the full stack trace?

**Comment by 4949Rodrigo** [comment]
Also when a URL json step in the code itself appears a corresponding error in the code:

if activity ['trends'] ['name']! = ""]

**Comment by 4949Rodrigo** [comment]
TypeError: string indices must be integers, not str

**Comment by ptwobrussell** [comment]
If you can provide a full console dump of your exact command and the stack trace as copied/pasted from your terminal, I might be able to further help you

**Comment by ptwobrussell** [comment]
Closing this issue since not enough info was provided to help you resolve the problem. Feel free to re-open if issues persist or you'd like to revisit. Thanks.
