### ISSUE TITLE
'module' object has no attribute 'Twitter' error

### ISSUE THREAD

**Issue by jamesmusick** [ptwobrussell/Mining-the-Social-Web#33]
I'm also getting the dreaded 'module' object has no attribute 'Twitter' error.
After reading through the comment threads & misc web forums I can confirm that
1. The dependent libraries are installed, in easy-install.pth & recognized by my IDE
2. I downloaded the entire repository (message 2 above this) to make sure that there wasn't a dependency I didn't realize
3. Using Pything 2.7.2 on a Mac OS 10.8.2 (and PyCharm, for what it's worth)
- Tried both the http://code.google.com version of the latest & the github version (I'm assuming github is most recent based on comments on the other site).
- Tried removing all files, the egg, etc & re-tracing my steps - same result.

Thanks for any help/suggestions.

-J

p.s. realized it would perhaps be more appropriate to open a new issue rather than comment on an old, closed issue.

**Comment by ptwobrussell** [comment]
I'm sorry for the delay in responding to this ticket. I must have overlooked the initial notification. Are you still having issues? Please re-open if so. If you are installing the latest version of the twitter package with "pip install twitter" or "easy_install twitter", I don't think you'll receive this same problem. It appears as though you are using the wrong package.
