### ISSUE TITLE
Question about Figure 5-1

### ISSUE THREAD

**Issue by matt-elson** [ptwobrussell/Mining-the-Social-Web#36]
Does someone know  how to draw  Figure 5-1. "The frequency of entities that have been retweeted by @timoreilly for a sample of recent tweets"?

e.g.
Is the figure drawn by Protovis?
if so,  how can I use Protovis to draw the figure?

A step by step explanation will be highly appreciated !

**Comment by ptwobrussell** [comment]
Good question. The bar charts in the book were all just copy/pastes from the output of the relevant script outputs into a spreadsheet program.
