### ISSUE TITLE
Hi there! We're gonna get you all set up to use MiningTheSocialWeb.

### ISSUE THREAD

**Issue by tourmaline612** [ptwobrussell/Mining-the-Social-Web#38]
wait for a long time, and then come out  "urllib2.URLError: <urlopen error [Errno 110] Connection timed out>" at last

**Comment by ptwobrussell** [comment]
I take it that you are trying to run the twitter__login.py script here? Can you confirm that you've filled in the necessary variables stubbed out at the top of that file and provide a little more information such as your version of the twitter package, version of Python, etc.?

**Comment by tourmaline612** [comment]
I am trying to run the friends_followers__get_friends.py script.And I find that it works well under win7, but doesn't work under linux.

**Comment by ptwobrussell** [comment]
With Twitter's v1.1 API and the recent commits for porting all Twitter code to the new API, this issue should effectively be resolved at this point. Please re-open if you find otherwise.
