### ISSUE TITLE
example 5-4 gives long error

### ISSUE THREAD

**Issue by soujiro0725** [ptwobrussell/Mining-the-Social-Web#39]
it might be similar to issue #9 
https://github.com/ptwobrussell/Mining-the-Social-Web/issues/9
But in my case, dateutil is not the case.

my environment;
MacOSX 10.6.8
Python 27
couchdb 1.2.0
python-couchdb 0.8
virtualenv 1.8.2

executing the code example 5-4 raises an error.
Do you have any idea why?

soichi
# ------error

(py27)soichi%                                                                  [~/Dropbox/Inspiron]
=CRASH REPORT==== 16-Dec-2012::20:24:29 ===
  crasher:
    initial call: couch_os_process:init/1
    pid: <0.6432.0>
    registered_name: []
    exception exit: {function_clause,
                        [{couch_os_process,handle_info,
                             [{#Port<0.2748>,
                               {data,
                                   {eol,
                                       <<"[[], [[null, 274152780170682369]]]">>}}},
                              {os_proc,
                                  "/Users/soichi/domains/py27/bin/couchpy",
                                  #Port<0.2748>,
                                  #Fun<couch_os_process.2.55582190>,
                                  #Fun<couch_os_process.3.55582190>,5000}],
                             [{file,"couch_os_process.erl"},{line,207}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,607}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]}
      in function  gen_server:terminate/6 (gen_server.erl, line 747)
    ancestors: [couch_query_servers,couch_secondary_services,
                  couch_server_sup,<0.31.0>]
    messages: []
    links: [<0.6431.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2584
    stack_size: 24
    reductions: 1741
  neighbours:
    neighbour: [{pid,<0.6430.0>},
                  {registered_name,[]},
                  {initial_call,{couch_work_queue,init,['Argument__1']}},
                  {current_function,{gen_server,loop,6}},
                  {ancestors,[<0.6428.0>]},
                  {messages,[]},
                  {links,[<0.6428.0>]},
                  {dictionary,[]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,233},
                  {stack_size,9},
                  {reductions,37}]
    neighbour: [{pid,<0.6433.0>},
                  {registered_name,[]},
                  {initial_call,{erlang,apply,2}},
                  {current_function,{gen,do_call,4}},
                  {ancestors,[]},
                  {messages,[]},
                  {links,[<0.6428.0>]},
                  {dictionary,
                      [{task_status_props,
                           [{changes_done,0},
                            {database,<<"tweets-user-timeline-timoreilly">>},
                            {design_document,<<"_design/index">>},
                            {progress,0},
                            {started_on,1355657069},
                            {total_changes,642},
                            {type,indexer},
                            {updated_on,1355657069}]},
                       {task_status_update,{{0,0,0},500000}}]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,610},
                  {stack_size,25},
                  {reductions,111}]
    neighbour: [{pid,<0.6429.0>},
                  {registered_name,[]},
                  {initial_call,{couch_work_queue,init,['Argument__1']}},
                  {current_function,{gen_server,loop,6}},
                  {ancestors,[<0.6428.0>]},
                  {messages,[]},
                  {links,[<0.6428.0>]},
                  {dictionary,[]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,987},
                  {stack_size,9},
                  {reductions,904}]
    neighbour: [{pid,<0.6428.0>},
                  {registered_name,[]},
                  {initial_call,{erlang,apply,2}},
                  {current_function,{gen,do_call,4}},
                  {ancestors,[]},
                  {messages,[]},
                  {links,[<0.6429.0>,<0.6431.0>,<0.6433.0>,<0.6430.0>,
                          <0.6424.0>]},
                  {dictionary,[]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,2584},
                  {stack_size,61},
                  {reductions,5322}]
    neighbour: [{pid,<0.6431.0>},
                  {registered_name,[]},
                  {initial_call,{erlang,apply,2}},
                  {current_function,{gen,do_call,4}},
                  {ancestors,[]},
                  {messages,
                      [{#Ref<0.0.0.76288>,
                        {ok,{json,
                                <<"{\"log\": \"Traceback (most recent call last):\n  File \\"/Users/soichi/domains/py27/lib/python2.7/site-packages/couchdb/view.py\\", line 79, in map_doc\n    results.append([[key, value] for key, value in function(doc)])\n  File \\"<string>\\", line 28, in entityCountMapper\nKeyError: 'hastags'\n\"}">>}}}]},
                  {links,[<0.6428.0>,<0.6432.0>]},
                  {dictionary,[]},
                  {trap_exit,false},
                  {status,runnable},
                  {heap_size,4181},
                  {stack_size,196},
                  {reductions,741}]
[error] [<0.6424.0>] *\* Generic server <0.6424.0> terminating 
*\* Last message in was {'EXIT',<0.6428.0>,
                        {function_clause,
                         [{couch_os_process,handle_info,
                           [{#Port<0.2748>,
                             {data,
                              {eol,<<"[[], [[null, 274152780170682369]]]">>}}},
                            {os_proc,
                             "/Users/soichi/domains/py27/bin/couchpy",
                             #Port<0.2748>,#Fun<couch_os_process.2.55582190>,
                             #Fun<couch_os_process.3.55582190>,5000}],
                           [{file,"couch_os_process.erl"},{line,207}]},
                          {gen_server,handle_msg,5,
                           [{file,"gen_server.erl"},{line,607}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,227}]}]}}
*\* When Server state == {group_state,undefined,
                         <<"tweets-user-timeline-timoreilly">>,
                         {"/usr/local/var/lib/couchdb",
                          <<"tweets-user-timeline-timoreilly">>,
                          {group,
                           <<237,92,122,114,162,28,196,163,160,252,121,84,46,
                             99,167,36>>,
                           nil,<<"_design/index">>,<<"python">>,[],
                           [{view,0,0,0,[],
                             <<"def entityCountMapper(doc):\n    if not doc.get('entities'):\n        import twitter_text\n        def getEntities(tweet):\n            extractor = twitter_text.Extractor(tweet['text'])\n            entities = {}\n            entities['user_mentions'] = []\n\n            for um in extractor.extract_mentioned_screen_names_with_indices():\n                entities['user_mentions'].append(um)\n            entities['hashtags'] = []\n            for ht in extractor.extract_hashtags_with_indices():\n                ht['text'] = ht['hashtag']\n                del ht['hashtag']\n                entities['hashtags'].append(ht)\n            entities['urls'] = []\n            for url in extractor.extract_urls_with_indices():\n                entities['urls'].append(url)\n            return entities\n\n        doc['entities'] = getEntities(doc)\n\n\n    if doc['entities'].get('user_mentions'):\n        for user_mention in doc['entities']['user_mentions']:\n            yield ('@' + user_mention['screen_name'].lower(), [doc['_id'], doc['id']])\n    if doc['entities'].get('hashtags'):\n        for hashtag in doc['entities']['hastags']:\n            yield ('#' + hashtag['text'], [doc['_id'], doc['id']])\n    if doc['entites'].get('urls'):\n        for url in doc['entites']['urls']:\n            yield (url['url'], [doc['_id'], doc['id']])">>,
                             nil,
                             [{<<"entity_count_by_doc">>,
                               <<"def summingReducer(keys, values, rereduce):\n    if rereduce:\n        return sum(values)\n    else:\n        return len(values)">>}],
                             []},
                            {view,1,0,0,[],
                             <<"def idMapper(doc):\n    yield(None, doc['id'])">>,
                             nil,
                             [{<<"max_tweet_id">>,
                               <<"def maxFindingReducer(keys, values, rereduce):\n    return max(values)">>}],
                             []}],
                           {[]},
                           nil,0,0,nil,nil}},
                         {group,
                          <<237,92,122,114,162,28,196,163,160,252,121,84,46,99,
                            167,36>>,
                          <0.6425.0>,<<"_design/index">>,<<"python">>,[],
                          [{view,0,0,0,[],
                            <<"def entityCountMapper(doc):\n    if not doc.get('entities'):\n        import twitter_text\n        def getEntities(tweet):\n            extractor = twitter_text.Extractor(tweet['text'])\n            entities = {}\n            entities['user_mentions'] = []\n\n            for um in extractor.extract_mentioned_screen_names_with_indices():\n                entities['user_mentions'].append(um)\n            entities['hashtags'] = []\n            for ht in extractor.extract_hashtags_with_indices():\n                ht['text'] = ht['hashtag']\n                del ht['hashtag']\n                entities['hashtags'].append(ht)\n            entities['urls'] = []\n            for url in extractor.extract_urls_with_indices():\n                entities['urls'].append(url)\n            return entities\n\n        doc['entities'] = getEntities(doc)\n\n\n    if doc['entities'].get('user_mentions'):\n        for user_mention in doc['entities']['user_mentions']:\n            yield ('@' + user_mention['screen_name'].lower(), [doc['_id'], doc['id']])\n    if doc['entities'].get('hashtags'):\n        for hashtag in doc['entities']['hastags']:\n            yield ('#' + hashtag['text'], [doc['_id'], doc['id']])\n    if doc['entites'].get('urls'):\n        for url in doc['entites']['urls']:\n            yield (url['url'], [doc['_id'], doc['id']])">>,
                            {btree,<0.6425.0>,nil,
                             #Fun<couch_btree.3.133731799>,
                             #Fun<couch_btree.4.133731799>,
                             #Fun<couch_view.less_json_ids.2>,
                             #Fun<couch_view_group.10.75991388>,snappy},
                            [{<<"entity_count_by_doc">>,
                              <<"def summingReducer(keys, values, rereduce):\n    if rereduce:\n        return sum(values)\n    else:\n        return len(values)">>}],
                            []},
                           {view,1,0,0,[],
                            <<"def idMapper(doc):\n    yield(None, doc['id'])">>,
                            {btree,<0.6425.0>,nil,
                             #Fun<couch_btree.3.133731799>,
                             #Fun<couch_btree.4.133731799>,
                             #Fun<couch_view.less_json_ids.2>,
                             #Fun<couch_view_group.10.75991388>,snappy},
                            [{<<"max_tweet_id">>,
                              <<"def maxFindingReducer(keys, values, rereduce):\n    return max(values)">>}],
                            []}],
                          {[]},
                          {btree,<0.6425.0>,nil,
                           #Fun<couch_btree.3.133731799>,
                           #Fun<couch_btree.4.133731799>,
                           #Fun<couch_btree.5.133731799>,nil,snappy},
                          0,0,nil,nil},
                         <0.6428.0>,nil,false,
                         [{{<0.139.0>,#Ref<0.0.0.76126>},650}],
                         <0.6427.0>,false}
*\* Reason for termination == 
*\* {function_clause,
       [{couch_os_process,handle_info,
            [{#Port<0.2748>,
              {data,{eol,<<"[[], [[null, 274152780170682369]]]">>}}},
             {os_proc,"/Users/soichi/domains/py27/bin/couchpy",#Port<0.2748>,
                 #Fun<couch_os_process.2.55582190>,
                 #Fun<couch_os_process.3.55582190>,5000}],
            [{file,"couch_os_process.erl"},{line,207}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}

=ERROR REPORT==== 16-Dec-2012::20:24:29 ===
*\* Generic server <0.6424.0> terminating 
*\* Last message in was {'EXIT',<0.6428.0>,
                        {function_clause,
                         [{couch_os_process,handle_info,
                           [{#Port<0.2748>,
                             {data,
                              {eol,<<"[[], [[null, 274152780170682369]]]">>}}},
                            {os_proc,
                             "/Users/soichi/domains/py27/bin/couchpy",
                             #Port<0.2748>,#Fun<couch_os_process.2.55582190>,
                             #Fun<couch_os_process.3.55582190>,5000}],
                           [{file,"couch_os_process.erl"},{line,207}]},
                          {gen_server,handle_msg,5,
                           [{file,"gen_server.erl"},{line,607}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,227}]}]}}
*\* When Server state == {group_state,undefined,
                         <<"tweets-user-timeline-timoreilly">>,
                         {"/usr/local/var/lib/couchdb",
                          <<"tweets-user-timeline-timoreilly">>,
                          {group,
                           <<237,92,122,114,162,28,196,163,160,252,121,84,46,
                             99,167,36>>,
                           nil,<<"_design/index">>,<<"python">>,[],
                           [{view,0,0,0,[],
                             <<"def entityCountMapper(doc):\n    if not doc.get('entities'):\n        import twitter_text\n        def getEntities(tweet):\n            extractor = twitter_text.Extractor(tweet['text'])\n            entities = {}\n            entities['user_mentions'] = []\n\n            for um in extractor.extract_mentioned_screen_names_with_indices():\n                entities['user_mentions'].append(um)\n            entities['hashtags'] = []\n            for ht in extractor.extract_hashtags_with_indices():\n                ht['text'] = ht['hashtag']\n                del ht['hashtag']\n                entities['hashtags'].append(ht)\n            entities['urls'] = []\n            for url in extractor.extract_urls_with_indices():\n                entities['urls'].append(url)\n            return entities\n\n        doc['entities'] = getEntities(doc)\n\n\n    if doc['entities'].get('user_mentions'):\n        for user_mention in doc['entities']['user_mentions']:\n            yield ('@' + user_mention['screen_name'].lower(), [doc['_id'], doc['id']])\n    if doc['entities'].get('hashtags'):\n        for hashtag in doc['entities']['hastags']:\n            yield ('#' + hashtag['text'], [doc['_id'], doc['id']])\n    if doc['entites'].get('urls'):\n        for url in doc['entites']['urls']:\n            yield (url['url'], [doc['_id'], doc['id']])">>,
                             nil,
                             [{<<"entity_count_by_doc">>,
                               <<"def summingReducer(keys, values, rereduce):\n    if rereduce:\n        return sum(values)\n    else:\n        return len(values)">>}],
                             []},
                            {view,1,0,0,[],
                             <<"def idMapper(doc):\n    yield(None, doc['id'])">>,
                             nil,
                             [{<<"max_tweet_id">>,
                               <<"def maxFindingReducer(keys, values, rereduce):\n    return max(values)">>}],
                             []}],
                           {[]},
                           nil,0,0,nil,nil}},
                         {group,
                          <<237,92,122,114,162,28,196,163,160,252,121,84,46,99,
                            167,36>>,
                          <0.6425.0>,<<"_design/index">>,<<"python">>,[],
                          [{view,0,0,0,[],
                            <<"def entityCountMapper(doc):\n    if not doc.get('entities'):\n        import twitter_text\n        def getEntities(tweet):\n            extractor = twitter_text.Extractor(tweet['text'])\n            entities = {}\n            entities['user_mentions'] = []\n\n            for um in extractor.extract_mentioned_screen_names_with_indices():\n                entities['user_mentions'].append(um)\n            entities['hashtags'] = []\n            for ht in extractor.extract_hashtags_with_indices():\n                ht['text'] = ht['hashtag']\n                del ht['hashtag']\n                entities['hashtags'].append(ht)\n            entities['urls'] = []\n            for url in extractor.extract_urls_with_indices():\n                entities['urls'].append(url)\n            return entities\n\n        doc['entities'] = getEntities(doc)\n\n\n    if doc['entities'].get('user_mentions'):\n        for user_mention in doc['entities']['user_mentions']:\n            yield ('@' + user_mention['screen_name'].lower(), [doc['_id'], doc['id']])\n    if doc['entities'].get('hashtags'):\n        for hashtag in doc['entities']['hastags']:\n            yield ('#' + hashtag['text'], [doc['_id'], doc['id']])\n    if doc['entites'].get('urls'):\n        for url in doc['entites']['urls']:\n            yield (url['url'], [doc['_id'], doc['id']])">>,
                            {btree,<0.6425.0>,nil,
                             #Fun<couch_btree.3.133731799>,
                             #Fun<couch_btree.4.133731799>,
                             #Fun<couch_view.less_json_ids.2>,
                             #Fun<couch_view_group.10.75991388>,snappy},
                            [{<<"entity_count_by_doc">>,
                              <<"def summingReducer(keys, values, rereduce):\n    if rereduce:\n        return sum(values)\n    else:\n        return len(values)">>}],
                            []},
                           {view,1,0,0,[],
                            <<"def idMapper(doc):\n    yield(None, doc['id'])">>,
                            {btree,<0.6425.0>,nil,
                             #Fun<couch_btree.3.133731799>,
                             #Fun<couch_btree.4.133731799>,
                             #Fun<couch_view.less_json_ids.2>,
                             #Fun<couch_view_group.10.75991388>,snappy},
                            [{<<"max_tweet_id">>,
                              <<"def maxFindingReducer(keys, values, rereduce):\n    return max(values)">>}],
                            []}],
                          {[]},
                          {btree,<0.6425.0>,nil,
                           #Fun<couch_btree.3.133731799>,
                           #Fun<couch_btree.4.133731799>,
                           #Fun<couch_btree.5.133731799>,nil,snappy},
                          0,0,nil,nil},
                         <0.6428.0>,nil,false,
                         [{{<0.139.0>,#Ref<0.0.0.76126>},650}],
                         <0.6427.0>,false}
*\* Reason for termination == 
*\* {function_clause,
       [{couch_os_process,handle_info,
            [{#Port<0.2748>,
              {data,{eol,<<"[[], [[null, 274152780170682369]]]">>}}},
             {os_proc,"/Users/soichi/domains/py27/bin/couchpy",#Port<0.2748>,
                 #Fun<couch_os_process.2.55582190>,
                 #Fun<couch_os_process.3.55582190>,5000}],
            [{file,"couch_os_process.erl"},{line,207}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
[error] [<0.6424.0>] {error_report,<0.30.0>,
                      {<0.6424.0>,crash_report,
                       [[{initial_call,
                          {couch_view_group,init,['Argument__1']}},
                         {pid,<0.6424.0>},
                         {registered_name,[]},
                         {error_info,
                          {exit,
                           {function_clause,
                            [{couch_os_process,handle_info,
                              [{#Port<0.2748>,
                                {data,
                                 {eol,
                                  <<"[[], [[null, 274152780170682369]]]">>}}},
                               {os_proc,
                                "/Users/soichi/domains/py27/bin/couchpy",
                                #Port<0.2748>,
                                #Fun<couch_os_process.2.55582190>,
                                #Fun<couch_os_process.3.55582190>,5000}],
                              [{file,"couch_os_process.erl"},{line,207}]},
                             {gen_server,handle_msg,5,
                              [{file,"gen_server.erl"},{line,607}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,227}]}]},
                           [{gen_server,terminate,6,
                             [{file,"gen_server.erl"},{line,747}]},
                            {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]}},
                         {ancestors,[<0.6423.0>]},
                         {messages,[]},
                         {links,[<0.6425.0>,<0.121.0>]},
                         {dictionary,[]},
                         {trap_exit,true},
                         {status,running},
                         {heap_size,1597},
                         {stack_size,24},
                         {reductions,476}],
                        []]}}

=CRASH REPORT==== 16-Dec-2012::20:24:29 ===
  crasher:
    initial call: couch_view_group:init/1
    pid: <0.6424.0>
    registered_name: []
    exception exit: {function_clause,
                        [{couch_os_process,handle_info,
                             [{#Port<0.2748>,
                               {data,
                                   {eol,
                                       <<"[[], [[null, 274152780170682369]]]">>}}},
                              {os_proc,
                                  "/Users/soichi/domains/py27/bin/couchpy",
                                  #Port<0.2748>,
                                  #Fun<couch_os_process.2.55582190>,
                                  #Fun<couch_os_process.3.55582190>,5000}],
                             [{file,"couch_os_process.erl"},{line,207}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,607}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]}
      in function  gen_server:terminate/6 (gen_server.erl, line 747)
    ancestors: [<0.6423.0>]
    messages: []
    links: [<0.6425.0>,<0.121.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1597
    stack_size: 24
    reductions: 476
  neighbours:
[error] [<0.139.0>] {error_report,<0.30.0>,
                     {<0.139.0>,crash_report,
                      [[{initial_call,
                         {mochiweb_acceptor,init,
                          ['Argument__1','Argument__2','Argument__3']}},
                        {pid,<0.139.0>},
                        {registered_name,[]},
                        {error_info,
                         {error,badarg,
                          [{erlang,list_to_binary,
                            [[{couch_os_process,handle_info,
                               [{#Port<0.2748>,
                                 {data,
                                  {eol,
                                   <<"[[], [[null, 274152780170682369]]]">>}}},
                                {os_proc,
                                 "/Users/soichi/domains/py27/bin/couchpy",
                                 #Port<0.2748>,
                                 #Fun<couch_os_process.2.55582190>,
                                 #Fun<couch_os_process.3.55582190>,5000}],
                               [{file,"couch_os_process.erl"},{line,207}]},
                              {gen_server,handle_msg,5,
                               [{file,"gen_server.erl"},{line,607}]},
                              {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,227}]}]],
                            []},
                           {couch_httpd,error_info,1,
                            [{file,"couch_httpd.erl"},{line,779}]},
                           {couch_httpd,send_error,2,
                            [{file,"couch_httpd.erl"},{line,883}]},
                           {couch_httpd,handle_request_int,5,
                            [{file,"couch_httpd.erl"},{line,345}]},
                           {mochiweb_http,headers,5,
                            [{file,"mochiweb_http.erl"},{line,136}]},
                           {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,227}]}]}},
                        {ancestors,
                         [couch_httpd,couch_secondary_services,
                          couch_server_sup,<0.31.0>]},
                        {messages,[]},
                        {links,[<0.123.0>,#Port<0.2745>]},
                        {dictionary,
                         [{mochiweb_request_qs,[{"group","true"}]},
                          {mochiweb_request_cookie,[]}]},
                        {trap_exit,false},
                        {status,running},
                        {heap_size,2584},
                        {stack_size,24},
                        {reductions,43524}],
                       []]}}

=CRASH REPORT==== 16-Dec-2012::20:24:29 ===
  crasher:
    initial call: mochiweb_acceptor:init/3
    pid: <0.139.0>
    registered_name: []
    exception error: bad argument
      in function  list_to_binary/1
         called as list_to_binary([{couch_os_process,handle_info,
                                    [{#Port<0.2748>,
                                      {data,
                                       {eol,
                                        <<"[[], [[null, 274152780170682369]]]">>}}},
                                     {os_proc,
                                      "/Users/soichi/domains/py27/bin/couchpy",
                                      #Port<0.2748>,
                                      #Fun<couch_os_process.2.55582190>,
                                      #Fun<couch_os_process.3.55582190>,5000}],
                                    [{file,"couch_os_process.erl"},
                                     {line,207}]},
                                   {gen_server,handle_msg,5,
                                    [{file,"gen_server.erl"},{line,607}]},
                                   {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,227}]}])
      in call from couch_httpd:error_info/1 (couch_httpd.erl, line 779)
      in call from couch_httpd:send_error/2 (couch_httpd.erl, line 883)
      in call from couch_httpd:handle_request_int/5 (couch_httpd.erl, line 345)
      in call from mochiweb_http:headers/5 (mochiweb_http.erl, line 136)
    ancestors: [couch_httpd,couch_secondary_services,couch_server_sup,
                  <0.31.0>]
    messages: []
    links: [<0.123.0>,#Port<0.2745>]
    dictionary: [{mochiweb_request_qs,[{"group","true"}]},
                  {mochiweb_request_cookie,[]}]
    trap_exit: false
    status: running
    heap_size: 2584
    stack_size: 24
    reductions: 43524
  neighbours:
[error] [<0.6425.0>] *\* Generic server <0.6425.0> terminating 
*\* Last message in was {'EXIT',<0.6424.0>,
                        {function_clause,
                         [{couch_os_process,handle_info,
                           [{#Port<0.2748>,
                             {data,
                              {eol,<<"[[], [[null, 274152780170682369]]]">>}}},
                            {os_proc,
                             "/Users/soichi/domains/py27/bin/couchpy",
                             #Port<0.2748>,#Fun<couch_os_process.2.55582190>,
                             #Fun<couch_os_process.3.55582190>,5000}],
                           [{file,"couch_os_process.erl"},{line,207}]},
                          {gen_server,handle_msg,5,
                           [{file,"gen_server.erl"},{line,607}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,227}]}]}}
*\* When Server state == {file,{file_descriptor,prim_file,{#Port<0.2747>,22}},
                              51}
*\* Reason for termination == 
*\* {function_clause,
       [{couch_os_process,handle_info,
            [{#Port<0.2748>,
              {data,{eol,<<"[[], [[null, 274152780170682369]]]">>}}},
             {os_proc,"/Users/soichi/domains/py27/bin/couchpy",#Port<0.2748>,
                 #Fun<couch_os_process.2.55582190>,
                 #Fun<couch_os_process.3.55582190>,5000}],
            [{file,"couch_os_process.erl"},{line,207}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}

=ERROR REPORT==== 16-Dec-2012::20:24:29 ===
*\* Generic server <0.6425.0> terminating 
*\* Last message in was {'EXIT',<0.6424.0>,
                        {function_clause,
                         [{couch_os_process,handle_info,
                           [{#Port<0.2748>,
                             {data,
                              {eol,<<"[[], [[null, 274152780170682369]]]">>}}},
                            {os_proc,
                             "/Users/soichi/domains/py27/bin/couchpy",
                             #Port<0.2748>,#Fun<couch_os_process.2.55582190>,
                             #Fun<couch_os_process.3.55582190>,5000}],
                           [{file,"couch_os_process.erl"},{line,207}]},
                          {gen_server,handle_msg,5,
                           [{file,"gen_server.erl"},{line,607}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,227}]}]}}
*\* When Server state == {file,{file_descriptor,prim_file,{#Port<0.2747>,22}},
                              51}
*\* Reason for termination == 
*\* {function_clause,
       [{couch_os_process,handle_info,
            [{#Port<0.2748>,
              {data,{eol,<<"[[], [[null, 274152780170682369]]]">>}}},
             {os_proc,"/Users/soichi/domains/py27/bin/couchpy",#Port<0.2748>,
                 #Fun<couch_os_process.2.55582190>,
                 #Fun<couch_os_process.3.55582190>,5000}],
            [{file,"couch_os_process.erl"},{line,207}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
[error] [<0.6425.0>] {error_report,<0.30.0>,
                      {<0.6425.0>,crash_report,
                       [[{initial_call,{couch_file,init,['Argument__1']}},
                         {pid,<0.6425.0>},
                         {registered_name,[]},
                         {error_info,
                          {exit,
                           {function_clause,
                            [{couch_os_process,handle_info,
                              [{#Port<0.2748>,
                                {data,
                                 {eol,
                                  <<"[[], [[null, 274152780170682369]]]">>}}},
                               {os_proc,
                                "/Users/soichi/domains/py27/bin/couchpy",
                                #Port<0.2748>,
                                #Fun<couch_os_process.2.55582190>,
                                #Fun<couch_os_process.3.55582190>,5000}],
                              [{file,"couch_os_process.erl"},{line,207}]},
                             {gen_server,handle_msg,5,
                              [{file,"gen_server.erl"},{line,607}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,227}]}]},
                           [{gen_server,terminate,6,
                             [{file,"gen_server.erl"},{line,747}]},
                            {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]}},
                         {ancestors,[<0.6424.0>,<0.6423.0>]},
                         {messages,[{'EXIT',<0.6427.0>,shutdown}]},
                         {links,[]},
                         {dictionary,[]},
                         {trap_exit,true},
                         {status,running},
                         {heap_size,987},
                         {stack_size,24},
                         {reductions,1189}],
                        []]}}

=CRASH REPORT==== 16-Dec-2012::20:24:29 ===
  crasher:
    initial call: couch_file:init/1
    pid: <0.6425.0>
    registered_name: []
    exception exit: {function_clause,
                        [{couch_os_process,handle_info,
                             [{#Port<0.2748>,
                               {data,
                                   {eol,
                                       <<"[[], [[null, 274152780170682369]]]">>}}},
                              {os_proc,
                                  "/Users/soichi/domains/py27/bin/couchpy",
                                  #Port<0.2748>,
                                  #Fun<couch_os_process.2.55582190>,
                                  #Fun<couch_os_process.3.55582190>,5000}],
                             [{file,"couch_os_process.erl"},{line,207}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,607}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,227}]}]}
      in function  gen_server:terminate/6 (gen_server.erl, line 747)
    ancestors: [<0.6424.0>,<0.6423.0>]
    messages: [{'EXIT',<0.6427.0>,shutdown}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 24
    reductions: 1189
  neighbours:

**Comment by ptwobrussell** [comment]
Are you still experiencing this error?

**Comment by soujiro0725** [comment]
No, it was my mistake in the code.  Thanks for you concern.

**Comment by ptwobrussell** [comment]
Looks like we can close this one given your previous comment. Thanks!
