### ISSUE TITLE
iPython -> IPython

### ISSUE THREAD

**Issue by Carreau** [ptwobrussell/Mining-the-Social-Web#43]
Hi, 

I saw here and there that IPython is written iPython.
I know Fernando Perez keep saying it shoudl be uper case I in his talks, 
so I guess when you have the occasion if you can update, it would be great. 

Thanks !

**Comment by ptwobrussell** [comment]
Sure, this is something I definitely want to make sure we do right. Where in particular are you seeing "IPython"?

**Comment by Carreau** [comment]
Hi, 

I saw "iPython" on a shared link on [nbviewer](http://nbviewer.ipython.org/urls/raw.github.com/ptwobrussell/Mining-the-Social-Web/master/ipython_notebooks/Chapter1.ipynb). 
I remember Fernando speeking "IPython" with uppercase I last year at SciPy, the I is for Interactive and is as much important as Python. I should also  have a chat history from him saying that `IPython` is great, `ipython` is acceptable, but that `iPython` could have the project in trouble with Apple.
