### ISSUE TITLE
Example 5-2 "the_tweet__extract_tweet_entities.py"

### ISSUE THREAD

**Issue by tsakamot** [ptwobrussell/Mining-the-Social-Web#44]
Hi,

I just tried to run "the_tweet__extract_tweet_entities.py", but it returned
 "{"errors":[{"message":"Bad Authentication data","code":215}]}", 
even though other examples which need login are working correctly so far.

I tried to put "t = login()" instead of "t = twitter.Twitter(domain='api.twitter.com', api_version='1.1')", and it looks working now.

Thank you.

**Comment by ptwobrussell** [comment]
Good catch. Commit 358cc71..0d092b6 fixes #44 as you described. Thank you for reporting it.
