### ISSUE TITLE
introduction__retweet_visualization.py

### ISSUE THREAD

**Issue by gavinerickson** [ptwobrussell/Mining-the-Social-Web#5]
Hi Matthew,

thanks for your very interesting book and the video too - that's what drew me in!

Anyway, I've never used python before. I've setup idle etc and have run the scripts in the early part of the book. But when i try and run this: introduction__retweet_visualization.py as a module in IDLE I get an error: 

line 13, in <module>
    Q = sys.argv[1]
IndexError: list index out of range

So is this where i add a query somehow, or have i got some sort of system setup error? i installed python 2.7 and the necessary libraries twitter etc...

**edit**
I got it running by taking out the offending line, and adding the search term directly into:

search_results.append(twitter_search.search(q="mysearchterm", rpp=100, page=page))

but i'm not sure if thats the way its supposed to work! (why was the Q=sys... there in the first place?) any help much appreciated, 

thanks,

Gavin

**Comment by ptwobrussell** [comment]
Gavin - 

Glad to hear from you. I'll help in any way that I can. One recommendation right away is that you should follow along with the official Python tutorial just to get down some of the basics. I promise it'll make the rest of your reading a lot more enjoyable.

In this case, the script is assuming that you're running it in a terminal and passing in an argument to it. For example, you might say "python introduction__retweet_visualization.py Gavin" to search for tweets that mention "Gavin" in them. Alternatively, you could hard code in a query by changing line 13 to Q = 'Gavin' or something like that. Make sense?

Let me know if you can get this working...

Regards - Matthew

---

http://www.linkedin.com/in/ptwobrussell

**Comment by gavinerickson** [comment]
Yup, I've got it working, thanks for the explanation about invoking the script from the command line. 

Can't put your book down! (if that's still meaningful in pdf times).

thanks again,

Gavin

**Comment by ptwobrussell** [comment]
Heh - really glad to hear it. Please let me know what else I can do to help you, and please consider spreading the word if you continue to find it enjoyable. Every constructive AMZN review is also really helpful.

Regards - Matthew

---

http://www.linkedin.com/in/ptwobrussell
