### ISSUE TITLE
Chapter 1 code error

### ISSUE THREAD

**Issue by wandeg** [ptwobrussell/Mining-the-Social-Web#61]
there is an error with the example code in chapter 1 in this line 
next_results = search_results['search_metadata']['next_results']

**Comment by ptwobrussell** [comment]
I believe I've fixed this issue in commit 16a06591aa7c9283db9ca4158eb3c40960aaaa19 - could you confirm and close the issue if you agree? This is the same issue as in #59 as far as I can tell.

**Comment by wandeg** [comment]
It works. :D Thanks!! Sorry I took so long to confirm.
