### ISSUE TITLE
couch db lucene mailboxes__couchdb_lucene.py error

### ISSUE THREAD

**Issue by toori67** [ptwobrussell/Mining-the-Social-Web#62]
I download file at http://zaffra.com/static/matthew/enron.mbox.json.gz. 
And I tried example 3-12. 
When I try to make index by_content, lucene print this error.
- _design/index caused TypeError: Cannot read property "length" from undefined

I figure out there are some enron mail data that don't contain 'parts' element.

So I fixed script.

``` javascript
if(doc.parts){
    for(var i=0;i<doc.parts.length;i++){
        ret.add(doc.parts[0].content); 
    }
}
```

This works fine.

**Comment by ptwobrussell** [comment]
This is very helpful. Thank you for debugging it. Do you also want to submit a pull request so that I can merge it into the codebase for everyone else to benefit from (and you'd get public kudos for contributing?) or do you want me to merge it in?

**Comment by toori67** [comment]
though I'm not that good at git...
So if you don't mind would you murge that code?

Anyway I'm fanatic reader of your book :)

2013년 7월 7일 일요일에 Matthew A. Russell님이 작성:

> This is very helpful. Thank you for debugging it. Do you also want to
> submit a pull request so that I can merge it into the codebase for everyone
> else to benefit from (and you'd get public kudos for contributing?) or do
> you want me to merge it in?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ptwobrussell/Mining-the-Social-Web/issues/62#issuecomment-20557150
> .

## 

_++++++++++++++++++++++++++++++++_
- Sung Min Lee*
  *
  *
- Undergraduate @ Dept.*\* of Computer Science *
- University of Seoul*
  *
  *
  - +82-10-654321-62*
    *
    *
    http://www.facebook.com/toori67
    http://kr.linkedin.com/pub/sung-min-lee/5a/a2/485http://wiki.uoscs.com/

_++++++++++++++++++++++++++++++++_

**Comment by ptwobrussell** [comment]
@toori67 Sure - I can merge it for you. Just remind me of the file you modified?

**Comment by toori67** [comment]
file : mailboxes__couchdb_lucene.py
line 21~23.

this file.

2013년 7월 7일 일요일에 Matthew A. Russell님이 작성:

> @toori67 https://github.com/toori67 Sure - I can merge it for you. Just
> remind me of the file you modified?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ptwobrussell/Mining-the-Social-Web/issues/62#issuecomment-20561597
> .

## 

_++++++++++++++++++++++++++++++++_
- Sung Min Lee*
  *
  *
- Undergraduate @ Dept.*\* of Computer Science *
- University of Seoul*
  *
  *
  - +82-10-654321-62*
    *
    *
    http://www.facebook.com/toori67
    http://kr.linkedin.com/pub/sung-min-lee/5a/a2/485http://wiki.uoscs.com/

_++++++++++++++++++++++++++++++++_
