### ISSUE TITLE
linkedin__analyze_titles.py not working

### ISSUE THREAD

**Issue by arizen-dev** [ptwobrussell/Mining-the-Social-Web#67]
I copied code exactly as here on github, but got an error - http://my.jetscreenshot.com/6808/20130726-ywqt-82kb

Meanwhile, this script linkedin__analyze_companies.py worked properly

**Comment by ptwobrussell** [comment]
@ibobriakov - I think the pull request I just merged in should have fixed this problem. The issue you were experiencing is that the PrettyTable API changed a while back and required some tweaks, but there are a few other important fixes in this latest commit, so I recommend updating your repository with a "git pull" or re-downloading your repository if you opted to download an archive of the files.

**Comment by arizen-dev** [comment]
Thanks for prompt reply, it indeed fixed this error :)

**Comment by ptwobrussell** [comment]
Very glad to hear it! Also, just in case you weren't already aware, the 2nd Edition of Mining the Social Web will be available soon, and the code repository is already available if you' d like to check it out. Feedback is always welcome - https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition

**Comment by arizen-dev** [comment]
That's very cool, thanks for sharing!
