### ISSUE TITLE
facebook__get_friends_rgraph.py

### ISSUE THREAD

**Issue by dagsonpatrick** [ptwobrussell/Mining-the-Social-Web#69]
Traceback (most recent call last):
  File "C:\Users\Dagson\Desktop\TCC-Pratica\Facebook\facebook__get_friends_rgraph.py", line 122, in <module>
    'out/jit')
  File "C:\Python27\lib\shutil.py", line 168, in copytree
    names = os.listdir(src)
WindowsError: [Error 3] O sistema não conseguiu localizar o caminho especificado: '../web_code/jit/_._'

---

line 119 shutil.rmtree('out/jit', ignore_errors=True)

line 121 shutil.copytree('../web_code/jit',
## line 122               'out/jit')

I'm not able to fix this error, I downloaded the 3 files located in https://github.com/ptwobrussell/Mining-the-Social-Web/tree/master/web_code/jit/rgraph link, I would know better about this function giving this error.

thank you

**Comment by ptwobrussell** [comment]
Can you confirm that you are working from a source code checkout of the entire GitHub repository and not just picking off a few files at a time? It appears at first glance that some required files are missing which is triggering an error during a file copy.

**Comment by dagsonpatrick** [comment]
Hello

ptwobrussell

I am working with local code.

Steps I follow to run the example facebook__get_friends_rgraph.py:

1ª downloaded the file facebook__get_friends_rgraph.py

2ª downloaded the following files to the same directory on my local machine

rgraph.css
rgraph.html
rgraph.js

the three above any files located in this https://github.com/ptwobrussell/Mining-the-Social-Web/tree/master/web_code/jit/rgraph

3ª modified the HTML_TEMPLATE = 'C: \ Users \ Dagson \ Desktop \ TCC-Practice \ Facebook \ jit \ rgraph.html'
- Wanted more explanation of each parameter of these two functions below that are giving error

shutil.rmtree ('out / jit' ignore_errors = True)

shutil.copytree ('.. / web_code / jit'
                 'out / jit')

note: I have done the previous examples the book and the chapter and got success ...

**Comment by dagsonpatrick** [comment]
Hello

ptwobrussell

example corrected

In my case the file was missing javascript "jit.js" on the local machine in a directory above.
- The call shutil.copytree ('src', 'target'), my problem was solved, src is the path of the folder that I created on my local machine, containing the 3 files mentioned in Step 2 of my comment.

thank you

**Comment by ptwobrussell** [comment]
Glad to hear it. I think I've mentioned this before, but you really should be working from a full download of the entire source code archive. Either do a git clone on the repository or download the latest zip archive to save yourself some of these problems in the future. Have fun!
