### ISSUE TITLE
Getting IPython to work

### ISSUE THREAD

**Issue by eoloughlin** [ptwobrussell/Mining-the-Social-Web#74]
I got to the "What Happens Next" point in the documentation at:

https://rawgithub.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition/master/ipynb/html/_Appendix%20A%20-%20Virtual%20Machine%20Experience.html

where it says... 

"At this point, an IPython Notebook server is running on your virtual machine, and you can access it from the web browser that you normally use on your host machine. Navigate to http://localhost:8888"

http://localhost:8888 is not working - I'm using Chrome at home, no proxy server.

How do I know if IPython Notebook is working?

**Comment by ptwobrussell** [comment]
Will pick this up on the 2nd Ed. page.
