### ISSUE TITLE
my chapter 6 python notebook won't load. version mismatch?

### ISSUE THREAD

**Issue by ghost** [ptwobrussell/Mining-the-Social-Web#75]
my chapter 6 python notebook won't load. The error message says :
"Error loading notebook
An unknown error occurred while loading this notebook. This version can load notebook formats v3 or earlier".

Is there a version mismatch for just that chapter? Could you help me resolve this. especially if I am going to use the vm as my dev environment, it would be so good to have this chapter up and running too.

**Comment by ghost** [comment]
Fixed. my fault!!! had a bad local file….

**Comment by ptwobrussell** [comment]
Great, glad it's all working now.
