### ISSUE TITLE
uppercase letters causing issues when used as couchdb table names (the_tweet__harvest_timeline.py)

### ISSUE THREAD

**Issue by rasper121** [ptwobrussell/Mining-the-Social-Web#8]
When using the script the_tweet__harvest_timeline.py, I had errors returned at the point of creation of db tables whenever a screen_names from twitter contained uppercase letters. I found that the install of couchdb on my windows machine did not by default allow uppercase letters in the database name, which causes a problem since twitter screen names often have uppercase letters. If anyone else's couch db installation has this limitation, I recommend some pre-processing of the twitter screen names to turn them all into lowercase before using them as part of a couchdb table name. Instead of line 66 which reads: DB = '%s-%s' % (DB, USER), my code uses the following lines:

screennamelower = USER.lower() # added to make names lowercase
DB = '%s-%s' % (DB, screennamelower)

**Comment by ptwobrussell** [comment]
Sorry for the delay in responding to you. I didn't realize that this would be an issue. Thanks for pointing it out. Have you discovered any other instances where screen names should be normalized to lower case? If you could send over a pull request with any of these changes, if there are any more, I'd appreciate it. Thanks again.
